# -*- coding: utf-8 -*-
"""AA_Project_Beerus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwUZn3jKTWLuqo1g0yqXdabJbfsvMA0d
"""

import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import json

response = pd.read_json('https://api.atlasacademy.io/export/JP/nice_servant_lore_lang_en.json')

print(response)

response.columns

response.head()

response.rarity.value_counts().plot(kind='barh', figsize=(8, 6) )

response.rarity.value_counts()

response.rarity.count()

response.pivot_table(index=['rarity', 'className'], aggfunc=lambda x: len(x.unique()))

df1 = response[['rarity', 'className', 'collectionNo']]
df_pivot = df1.pivot_table(index=['rarity', 'className'], aggfunc=lambda x: len(x.unique()))

fig = df_pivot.plot(kind='barh', figsize=(15, 18), grid = 'True')

# plt.rcParams['figure.facecolor'] = "white"
fig.figure.savefig('distribution.png', transparent=False)

df_pivot.columns

df1.rarity.describe()

df1.className.value_counts()

df1.rarity.value_counts()

df_pivot

df_pivot.to_csv('distribution.csv')